name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  schedule: # monthly
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:noetic-ros-base
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: noetic
      - name: Build
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros1-distro: noetic
          vcs-repo-file-url: .rosinstall
